# Generated by Django 5.1.6 on 2025-02-18 09:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('international', 'International')], max_length=50)),
                ('category', models.CharField(choices=[('construction', 'Construction'), ('it', 'Information Technology'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('infrastructure', 'Infrastructure'), ('energy', 'Energy'), ('transportation', 'Transportation'), ('telecommunications', 'Telecommunications'), ('agriculture', 'Agriculture'), ('defense', 'Defense')], max_length=50)),
                ('deadline', models.DateTimeField()),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('location', models.CharField(max_length=100)),
                ('requirements', models.TextField(blank=True)),
                ('scope', models.TextField(blank=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.tender')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tender')},
            },
        ),
        migrations.AddField(
            model_name='tender',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_tenders', through='tenders.TenderFavorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['type'], name='tenders_ten_type_2436ab_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['category'], name='tenders_ten_categor_51be61_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['status'], name='tenders_ten_status_955cba_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['deadline'], name='tenders_ten_deadlin_585934_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['location'], name='tenders_ten_locatio_8e7dcf_idx'),
        ),
    ]
